# Generated by Django 5.1.7 on 2025-04-01 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WeatherData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=120)),
                ("state", models.CharField(max_length=120)),
                ("country", models.CharField(max_length=100)),
                ("temperature", models.FloatField()),
                ("time", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-time"],
            },
        ),
    ]
