# Generated by Django 5.1.7 on 2025-04-01 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="weatherdata",
            options={
                "ordering": ["-time"],
                "verbose_name": "Weather Data",
                "verbose_name_plural": "Weather Data",
            },
        ),
    ]
